# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SQLite.swift', '~> 0.14.1'

  # Pods for iosApp

end
